### ISSUE TITLE
It doesn't work for the root folder

### ISSUE THREAD

**Issue by lukaszpolowczyk** [tpina/import-file-to-folder#6] opened 2020-09-13 12:46 UTC
There is no method to add a file to the root folder when I don't have many folders in my workspace. The main folder is not visible in sidebar when I don't have many folders in workspace.

Please add add function to root folder.

**Comment by tpina** [comment] 2020-09-14 13:33
Hi @lukaszpolowczyk,

Thanks for filing this. I will try to carve out some spare time to fix this asap.

**Comment by tpina** [comment] 2020-09-28 17:34
@lukaszpolowczyk Fixed!

**Comment by lukaszpolowczyk** [comment] 2020-09-28 18:04
@tpina It still doesn't work for me. I have version 0.10.0
You get both the import successful message and the same error as before.
But the file in the root folder does not appear.

**Comment by tpina** [comment] 2020-09-28 18:18
@lukaszpolowczyk - Weird I am unable to reproduce. Have you tried to remove and reinstall the extension?

Can you kindly provide the path you're trying to import the file into? Does it have special characters?

**Comment by lukaszpolowczyk** [comment] 2020-09-28 18:46
@tpine path is `/home/lp/new` - text file

"Have you tried to remove and reinstall the extension?"
Yes, I did it now and it makes no difference.

**Comment by tpina** [comment] 2020-09-28 19:31
@lukaszpolowczyk I did this fix on a windows machine - Need to check on a unix based system. Apologies for this.

Will try to fix it soon.

**Comment by tpina** [comment] 2020-10-12 19:26
@lukaszpolowczyk I just tried this on a MacBook and it is working fine. Are you using Linux?

**Comment by lukaszpolowczyk** [comment] 2020-10-12 23:56
@tpina Yes, I use Linux.

**Comment by tpina** [comment] 2020-10-14 13:43
@lukaszpolowczyk I am not able to reproduce this issue on Ubuntu.

![Screen-Recording-2020-10-14-at-1](https://user-images.githubusercontent.com/3940434/95997329-94565300-0e2b-11eb-85cb-d32759772df6.gif)

**Comment by lukaszpolowczyk** [comment] 2020-10-14 14:27
@tpina Arch Linux and Cinnamon, [vscode AUR](https://aur.archlinux.org/packages/visual-studio-code-bin/):
![import file vscode - Peek 2020-10-14 16-25](https://user-images.githubusercontent.com/16800535/96003197-4432bd00-0e3a-11eb-9b12-389f8084280c.gif)

**Comment by tpina** [comment] 2020-10-15 08:42
@lukaszpolowczyk it should be fixed by now. The context menu was being invoked but a file was selected. It was trying to import the new file into a file.

**Comment by lukaszpolowczyk** [comment] 2020-10-15 16:14
@tpina Now it is working. Thanks.

**Closed as completed** 2020-10-16 15:19 UTC
